name: Continuous itegration and deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses : actions/checkout@v3

      - name : Setup .Net 9
        uses : actions/setup-dotnet@v3
        with : 
          dotnet-version: '9.0.*'

      - name: Restore dependencies
        run: dotnet Restore

      - name: Add Microsoft.Extensions.DependencyInjection
        run: dotnet add MasterServiceDemo/MasterServiceDemo/MasterServiceDemo.csproj package Microsoft.Extensions.DependencyInjection --version 9.0.1

      - name: Build app
        run: dotnet build MasterServiceDemo/MasterServiceDemo/MasterServiceDemo.csproj -c Release --no-restore

      - name : Test app
        run : dotnet test MasterServiceDemo/MasterServiceDemoTest/MasterServiceDemoTest.csproj -c Release --no-build





