name: Continuous itegration and deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses : actions/checkout@v3

      - name : Setup .Net 8
        uses : actions/setup-dotnet@v3
        with : 
          dotnet-version: '8.0.*'

      - name: Restore dependencies
        run: dotnet Restore

      - name: Build app
        run: |
          for sln in $(find . -name "*.sln"); do
            echo "Building solution: $sln"
            dotnet build "$sln" -c Release --no-restore
          done






